services:
  db:
    container_name: postgres_container
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: db
    volumes:
      - ./postgres/data_db:/var/lib/postgresql/data
      - ./postgres/airflow_init.sql:/docker-entrypoint-initdb.d/airflow_init.sql
    networks:
      - my_network

  af:
    container_name: airflow_container
    build: .
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow_password@db:5432/airflow_db
      DB_HOST: db
      GENIUS_ACCESS_TOKEN: ${GENIUS_ACCESS_TOKEN}
      # Load other env vars if needed
      POSTGRES_USER: ${POSTGRES_USER:-db_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-db_password}
      POSTGRES_DB: ${POSTGRES_DB:-db}
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./:/opt/airflow/project
    depends_on:
      - db
    networks:
      - my_network
    command: >
      bash -c "airflow db migrate && airflow standalone"

networks:
  my_network:
    driver: bridge
